version: "3"
services:
  nginx:
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    build:
      dockerfile: Dockerfile
      context: ./data/nginx
    restart: always
    networks:
      - network-app
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#
#  certbot:
#    image: certbot/certbot
#    restart: unless-stopped
#     networks:
#       - network-app
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  network-app:
    driver: bridge 
